<a href="https://colab.research.google.com/github/saadz-khan/tukl-intern-prog/blob/master/pytorch_practice_Self.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Self Practice of Pytorch


In [1]:
# Importing Libraries
import torch

In [7]:
device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor = torch.tensor([[1, 2, 3], [4,5,6]], dtype = torch.float32, device = device, requires_grad = True)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)


In [10]:
my_tensor.shape

torch.Size([2, 3])

In [21]:
t = torch.linspace(start=0.1, end=1,  steps=10)
u = torch.arange(start=0, end=5, step=1)
v = torch.ones((3,3))
w = torch.eye(5,5)
x = torch.empty(size=(3,3), dtype=torch.float32, requires_grad=True)
y = torch.randn(size=(3,3), dtype=torch.float32, requires_grad=True)
z = torch.zeros(size=(3,3), dtype=torch.float32, requires_grad=True)
z1 = torch.empty(size=(1,5)).normal_(mean=0, std=1)

print(t)
print(u)
print(v)
print(w)
print(x)
print(y)
print(z)
print(z1)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
tensor([0, 1, 2, 3, 4])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[2.2515e-04, 3.0665e-41, 1.0000e+00],
        [1.0000e+00, 1.0000e+00, 1.0000e+00],
        [1.0000e+00, 1.0000e+00, 1.0000e+00]], requires_grad=True)
tensor([[-0.3380, -0.4183, -0.7993],
        [ 0.0222,  1.9862, -0.7579],
        [ 2.3066,  0.7977, -1.6086]], requires_grad=True)
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], requires_grad=True)
tensor([[-0.2079, -0.4780, -0.2063, -0.6570,  0.4704]])


In [22]:
import numpy as np
np_array = np.zeros((3,3))
conv_tensor = torch.from_numpy(np_array)
conv_tensor 

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [35]:
z = x + y # Best for Addition and Subtraction.

# Division
z = torch.true_divide(x, y)

# inplace operations
t = torch.zeros(3,3)
t.add_(x)
t += x # Computational Less expensive steps
t

# Exponentials
z = x.pow(2)
z

# Comparison
z = x > 0
z = x < 0

# Matrix Mul
x1 = torch.randn((2,5))
x2 = torch.randn((5,3))
x3 = torch.mm(x1, x2)
x3.shape

# Matrix powers

print(y.matrix_power(3))

# Dot Product 1D Tensors 
x1 = torch.randn((2))
x2 = torch.randn((2))
torch.dot(x1,x2)

tensor([[ 4.8785, -0.4143, -0.6175],
        [-0.0484,  7.0894, -0.6677],
        [ 1.8188,  0.6639,  3.8534]], grad_fn=<MmBackward>)


tensor(-0.0482)

In [37]:
sum_x = torch.sum(x, dim=0)
values, indices = torch.max(x, dim=0)
print(values) 
print(indices)

values, indices = torch.min(x, dim=0)
print(values) 
print(indices)
z = torch.argmax(x,dim=0)
z

tensor([1., 1., 1.], grad_fn=<MaxBackward0>)
tensor([1, 1, 0])
tensor([2.2515e-04, 3.0665e-41, 1.0000e+00], grad_fn=<MinBackward0>)
tensor([0, 0, 0])


tensor([1, 1, 0])